{
	"ActionResult": {
		"_Name": "sync"
	},
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "WorkerSet",
			"Query": "WorkerSet"
		}
	],
	"OnFailure": "/DemoSebenza/Actions/Service/SyncFailureMessage.action",
	"Service": "/DemoSebenza/Services/demoSebenza.service",
	"_Type": "Action.Type.OfflineOData.Download"
}