{
	"Service": "/DemoSebenza/Services/demoSebenza.service",
	"DefiningRequests": [
	{
		"Name": "Customers",
		"Query": "Customers"
	},
	{
		"Name": "Suppliers",
		"Query": "Suppliers"
	},
	{
		"Name": "Products",
		"Query": "Products"
	},
	{
		"Name": "SalesOrderHeaders",
		"Query": "SalesOrderHeaders"
	},
	{
		"Name": "SalesOrderItems",
		"Query": "SalesOrderItems"
	},
	{
		"Name": "PurchaseOrderItems",
		"Query": "PurchaseOrderItems"
	}
],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/DemoSebenza/Actions/Service/SyncFailureMessage.action"
}