{
	"ActionResult": {
		"_Name": "init"
	},
	"ActivityIndicatorText": "Downloading...",
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "WorkerSet",
			"Query": "WorkerSet"
		}
	],
	"OnFailure": "/DemoSebenza/Actions/Service/InitializeOfflineFailureMessage.action",
	"OnSuccess": "/DemoSebenza/Actions/Service/InitializeOfflineSuccessMessage.action",
	"Service": "/DemoSebenza/Services/demoSebenza.service",
	"ShowActivityIndicator": true,
	"_Type": "Action.Type.ODataService.Initialize"
}