{
	"CreateLinks": [
		{
			"Property": "SalesOrders",
			"Target": {
				"EntitySet": "SalesOrderHeaders",
				"QueryOptions": "$filter=GrossAmount eq {{#Page:Enter_Job/#Control:FCofferAmt/#Value}}"
			},
			"_Enabled": true
		}
	],
	"OnFailure": "/DemoSebenza/Actions/CreateJobFailureMessage.action",
	"OnSuccess": "/DemoSebenza/Actions/CloseModalPage_Complete.action",
	"Properties": {
		"City": "#Page:Enter_Job/#Control:FCCreateLocation/#Value"
	},
	"Target": {
		"EntitySet": "Customers",
		"Service": "/DemoSebenza/Services/demoSebenza.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}